### ISSUE TITLE
Error: There isn't a HAP Characteristic state

### ISSUE THREAD

**Issue by alexfonseca** [michaelmcneela/homebridge-visonic-powerlink2#4]
I've just installed and I am having the following error

Error polling: Error: There isn't a HAP Characteristic state which corresponds with the PowerLink2's current status – the system may be starting to arm

**Comment by alexfonseca** [comment]
and now new error is just showing:

[4/18/2022, 4:57:20 PM] Homebridge v1.4.0 (HAP v0.10.0)

/homebridge/node_modules/homebridge-visonic-powerlink2/node_modules/one-concurrent/index.js:35
                                callback.apply(this, arguments); // Call this stored callback, with any/all arguments that were provided
             ^
TypeError: Cannot read property 'timeout' of undefined
    at /homebridge/node_modules/homebridge-visonic-powerlink2/node_modules/visonic-powerlink2/index.js:219:50
    at fauxCallback (/homebridge/node_modules/homebridge-visonic-powerlink2/node_modules/one-concurrent/index.js:35:14)
    at Request._callback (/homebridge/node_modules/homebridge-visonic-powerlink2/node_modules/visonic-powerlink2/index.js:192:3)
    at Request.self.callback (/homebridge/node_modules/homebridge-visonic-powerlink2/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-visonic-powerlink2/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-visonic-powerlink2/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
[4/18/2022, 4:57:20 PM] [Amarelinha] Child bridge process ended

**Comment by alexfonseca** [comment]
To solve the second issue I used the forked version.
Now on restart
[4/18/2022, 5:01:29 PM] Registering accessory 'homebridge-visonic-powerlink2.PowerLink2'
[4/18/2022, 5:01:29 PM] [Amarelinha] Loaded homebridge-visonic-powerlink2 v1.0.1 child bridge successfully
[4/18/2022, 5:01:29 PM] Loaded 0 cached accessories from cachedAccessories.0EEB9DDE5D2F.
[4/18/2022, 5:01:29 PM] Homebridge v1.4.0 (HAP v0.10.0) (Amarelinha) is running on port 36495.
[4/18/2022, 5:01:31 PM] [Amarelinha] Error polling: Error: Error getting raw status: Error: ESOCKETTIMEDOUT
[4/18/2022, 5:01:43 PM] [Amarelinha] Error polling: Error: There isn't a HAP Characteristic state which corresponds with the PowerLink2's current status – the system may be starting to arm

**Comment by alexfonseca** [comment]
In understand now I cannot activate the plugin as an isolated child bridge. This causes the error above.
Now the system works n homebridge directly, but on apple homekit always is giving error with "Accessory is not answering" and I have a periodic fail in homebridge log:

[4/18/2022, 8:48:44 PM] [PowerLink2] Error polling: Error: There isn't a HAP Characteristic state which corresponds with the PowerLink2's current status – the system may be starting to arm
[4/18/2022, 8:48:57 PM] [PowerLink2] Error polling: Error: Error getting raw status: Error: ESOCKETTIMEDOUT
[4/18/2022, 9:01:27 PM] [Visonic] Error polling: Error: Error getting raw status: Error: Failed to get authentication cookie: Error: ETIMEDOUT
